name: Data Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  db-charm-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/postgresql-operator
            commit: fa7d3e432561540b5e4c3b211a421b4c13d64a5f  # rev557 rev556 2025-02-04T14:01:18Z
          - charm-repo: canonical/postgresql-k8s-operator
            commit: 9ed1b7ced2a0f68c49f5f493569bd40bc72e1166  # 2025-02-04T21:07:50Z
          - charm-repo: canonical/mysql-operator
            commit: 9530600dacc7a4c9c326c9bbf09f6670c245081b  # rev343 rev342 2025-01-31T14:00:16Z
          - charm-repo: canonical/mysql-k8s-operator
            commit: 1301de05c224e0557b373445ff333fa85d404710  # rev224 rev223 2025-01-31T14:00:53Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Checkout the operator repository
        uses: actions/checkout@v4
        with:
          path: myops

      - name: Install patch dependencies
        run: pip install poetry~=2.0

      - name: Update 'ops' dependency in test charm to latest
        run: |
          if [ -e "requirements.txt" ]; then
            sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
            echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
          else
            sed -i -e "s/^ops[ ><=].*/ops = {path = \"myops\"}/" pyproject.toml
            poetry lock
          fi

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit
