name: Observability Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            commit: 196e744519f891d3cd43a20caf3d4f5329470a89  # rev150 2025-02-03T10:53:31Z
          - charm-repo: canonical/prometheus-k8s-operator
            commit: c6c40f36c9bcdcbaad787e8995c6753a8c957434  # 2025-01-29T11:26:48Z
          - charm-repo: canonical/grafana-k8s-operator
            commit: 86aa2d1bfe9ea12017674646d57a52777cfc077f  # 2025-01-30T09:08:25Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        if: ${{ !(matrix.disabled) }}
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        if: ${{ !(matrix.disabled) }}
        run: tox -vve static-charm
